version: '3.8'

services:
  frontend:
    build: ./ids-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./Python
    ports:
      - "5001:5001"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccountKey.json